<?php
/**
 * Created by PhpStorm.
 * User: shooke
 * Date: 17-2-15
 * Time: 上午10:24
 */

namespace corephp\coredb\query;


class Mysql extends Query
{
    public function insert()
    {
    }

    public function replace()
    {
    }

    public function update()
    {
    }

    public function delete()
    {
    }

    public function one()
    {
    }

    public function all()
    {
    }

    public function count($field = '*')
    {
        return parent::count($field); // TODO: Change the autogenerated stub
    }

    public function max($field)
    {
        return parent::max($field); // TODO: Change the autogenerated stub
    }

    public function min($field)
    {
        return parent::min($field); // TODO: Change the autogenerated stub
    }

    public function avg($field)
    {
        return parent::avg($field); // TODO: Change the autogenerated stub
    }

    public function sum($field)
    {
        return parent::sum($field); // TODO: Change the autogenerated stub
    }
}